matrix:
  allow_failures:
    - os: osx
  include:
    - before_install:
        - brew update && brew install awscli mysql upx python wxpython
        - pip2 install --upgrade cython numpy scipy
      os: osx
      osx_image: xcode8.3
      python: 2.7.12
